name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debian:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set-up toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: linter
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    - name: Prepare Debian build
      run: |
        sudo apt-get update
        sudo apt-get install debhelper cargo libssl-dev
        mkdir -p debian-packaging
        rsync -av --exclude='debian-packaging' . debian-packaging/
    - name: Build Debian Package
      run: |
        cd debian-packaging
        dpkg-buildpackage -uc -us
    - uses: actions/upload-artifact@v1
      with:
        name: s7-1200-web-control_0.1.0-0_amd64.deb
        path: ./s7-1200-web-control_0.1.0-0_amd64.deb

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set-up toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build exe
      run: |
        cargo build --release
    - uses: actions/upload-artifact@v1
      with:
        name: s7-1200-web-control.exe
        path: ./target/release/s7-1200-web-control.exe

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-windows, build-debian]
    steps:
    - name: Create a Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - name: Upload Release Asset Windows
      id: upload-release-asset-windows 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./s7-1200-web-control.exe/s7-1200-web-control.exe
        asset_name: s7-1200-web-control.exe
        asset_content_type: application/octet-stream
    - name: Upload Release Asset Linux
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./s7-1200-web-control_0.1.0-0_amd64.deb/s7-1200-web-control_0.1.0-0_amd64.deb
        asset_name: s7-1200-web-control_0.1.0-0_amd64.deb
        asset_content_type: application/octet-stream